### PR TITLE
Add example for multiple consumers with topic routing based on queue

### PR DESCRIPTION
**Pull request by matmar10**
This reproduces issue #20 

Usage:

```
npm install
node demo/topic/subscriber.js
(and in separate console window)
node demo/topic/publisher-topic.js
```

### CODE REVIEW

**Comment by arobson** [comment]
@matmar10 - so the good news is there's a good explanation for why you're seeing this. Rabbot will only create a single connection per connection name, per process, regardless of the number of times you call topology. I think in order to get the behavior you want, maybe try start separate processes for each of the subscribers. I haven't tried this yet and only had a brief moment to glance at the code, but I suspect this is the issue. If that isn't what's happening, I'll dig in and take a closer look. Thanks for submitting code for this, it makes it a lot easier for me to try and help.

**Comment by matmar10** [comment]
@arobson thanks so much for having a look and your lightning fast response. 

So if I understand correctly, I should be able to create multiple named connections? Running in separate processes is not really a viable option in my case (since I pay per process on my hosted environment). 

Can you advise how to do this with multiple named connections? Will have a crack but figured I'd ask since you might be able to save me a bunch of time toying with toplogy setup w/ named connections.

**Comment by matmar10** [comment]
Ah - bingo!!! This worked. Using multiple named connections got it working. Leaving the PR open since you may want to add this demo as I'm sure someone else may find it useful.

**Comment by matmar10** [comment]
Alas, after further review it seems this did not work. I've updated the PR to try to use multiple connections - can you have a look?

The actual behavior was that both left and right handlers received messages for the `left` queue. This is clear because the `right` queue fills up and does not drain, and the following log output:
```
LEFT Received: {"message":"Message 9990"} routingKey: left
RIGHT Received: {"message":"Message 9990"} routingKey: left
LEFT Received: {"message":"Message 9992"} routingKey: left
RIGHT Received: {"message":"Message 9992"} routingKey: left
LEFT Received: {"message":"Message 9994"} routingKey: left
RIGHT Received: {"message":"Message 9994"} routingKey: left
LEFT Received: {"message":"Message 9996"} routingKey: left
RIGHT Received: {"message":"Message 9996"} routingKey: left
LEFT Received: {"message":"Message 9998"} routingKey: left
RIGHT Received: {"message":"Message 9998"} routingKey: left
```

**Comment by matmar10** [comment]
Any pointers?

**Comment by arobson** [comment]
@matmar10 - I am probably missing the goal of the use case. If I understand what you'd like to do with this, I can help you design a topology that will do what you'd like. In the meantime, I'm going to guess and give you some steps and we'll see how close I get to what you actually want to accomplish 😄 

### Step 1 - 1 process for publisher and 1 process for all subscribers

What I currently understand is that you'd like to limit your publisher and subscriber to a single process each because you have to pay your hosting provider per process, correct? If that's the case, let's keep this to a single connection for both the publisher and the subscriber. AMQP multiplexes channels onto a single TCP/IP connection. Having more than one without increasing the number of processes will be very unlikely to increase the number of messages we can handle.

Rabbot will create a channel per queue and so you will get concurrent delivery for each queue your subscriber process is actively subscribed to. This won't give you pure parallelism, but if you need it, you'll be willing to pay for more processes ;)

### Step 2 - Simplify the topology call
Pull out the special logic and make 1 call to topology on the subscriber side. Multiple calls to rabbot configure with the same connection name get no op'd because, in the predecessor lib, folks misunderstood the intent and would make that call over and over in a loop and end up with huge memory leaks (long story).

Within a single process, you want to setup everything you expect rabbot to establish/assert within that call once and then between disconnects, it will attempt to re-establish those things so your service can continue to operate. Having conditionals in there or calling it multiple times for a service makes that harder to reason about, so either you want to have a separate topology call per connection and just repeat the shared bits so its clear what pieces are being repeated between connections or just avoid having multiple connections per process if you can.

The multiple connection feature is primarily there to support the creation of messaging bridges between brokers and vhosts.

### Step 3 - Publish different message types
The original way the handlers are written doesn't make a lot of sense because they're both written to handle every message from every queue the process is subscribed to. I don't know why you'd want to do that and it's clear you just wanted to test some things out, nothing wrong with that.

In message based systems, the message is the contract, not the topology. Rabbot handler's are intentionally designed to handle messages based on type, not where the message comes from. This is because, ideally, you shouldn't care how the message got to you, only what the message means. 

I understand many of us must operate outside of ideals, so if you absolutely need to include where the message came from as part of how the message is handled, Rabbot also supports this behavior. [https://github.com/arobson/rabbot#handle-typename-handler-queuename-context-](See the readme for examples). Please keep in mind though, most of the time, I'd advise you to avoid this because I think it's going to make things harder in the long run.

Either way, you can simplify your topology and just auto-subscribe to both queues with a single topology call.

**Comment by matmar10** [comment]
Thanks, @arobson  - this was helpful. My confusion stemmed from the way topology is defined in the examples (with conditionals for queue binding). Now that you've cleared that ip for me, I was able to get things working in my topic example both using `type` and also binding to a specific queue (using options for `.handle` method. 

Thanks again for the great assistance. 

FWIW the example I've added shows how this can be done.

**Pull request merged**
