### PR TITLE
feat: add passive option to queue

### PR DESCRIPTION
**Pull request by zlintz**
allows for checkQueue instead of assertQueue when clients have restricted permissions

fixes issue #183

### CODE REVIEW

**Comment by zlintz** [comment]
Thanks for any of your time in advance for considering this!

**Comment by zlintz** [comment]
I am happy to hear any feedback as well

**Comment by zlintz** [comment]
Just wanted to follow up on this as I haven't heard anything yet

**Comment by codepushr** [comment]
I really need this feature too... how come nobody reacted for this long?

**Comment by zlintz** [comment]
Not sure but I am planning to clone this repo to start maintaining this if things don't start happening.  @arobson I would love to help to continue this one if possible.

**Comment by zlintz** [comment]
Moving to something I can maintain unfortunately.
If anyone is interested -> https://github.com/zlintz/foo-foo-mq

**Pull request closed without merging**
