### PR TITLE
fix(reply): reply multiple times fixed in noBatch mode

### PR DESCRIPTION
**Pull request by Cyri-L**
when noBatch mode activated, replying multiple times to the same request caused an error. This has been fixed by calling just once ack() in the reply method

### CODE REVIEW

**Comment by arobson** [comment]
@Cyri-L - another great find and fix. I really appreciate the PRs. Before I get this one merged and published, I'd like to get a test in place for this one so it doesn't get broken in the future through a regression. If you get to it before I do, that's awesome, otherwise, it'll probably be this weekend before I get it done.

Thanks again for your contributions, I'll get you added to the list in the package file.

**Comment by Cyri-L** [comment]
Your library is really great! 

As an input, I think It should be helpful to be able to isolate by Broker, in short: 
var Broker = require("rabbot");
var newBroker = new Broker();
By this, we could give the ability to group consumers, publishers by "micro-service".

Besides that, I am trying to dynamically change the prefetch count of a channel, but couldn't work out.
Would you have some hints?

I am trying stuff like this,unsuccessfully:
 this.limitRequest = (count) => {
        rabbot.
            connections[CONNECTION_NAME].channels["queue:" + Q_REQUESTS.name]
            .queue.channel.prefetch(count);
        
        rabbot.
            connections[CONNECTION_NAME].channels["exchange:" + EXCHANGE_REQUESTS.name]
            .exchange.channel.prefetch(count);
    };

**Comment by arobson** [comment]
@Cyri-L - thanks for the feedback. You can separate multiple connections presently. I understand that's probably not as convenient a conceptual model. I'd like to understand your use case for wanting multiple broker instances within the same process.

Check out https://github.com/arobson/rabbot#channel-prefetch-limits. That lets you set prefetch limits. I don't presently have an API call that would give you the ability to change it, but that could be added. It'd take some effort primarily because the planets need to be aligned before you can make the call since post Rabbit 3.3.0 prefetching gets set per consumer. So now, instead of just having 5 preconditions to meet, rabbot has to ensure that the connection, exchange, queue, binding, channel and consumer all exist before trying to set this. In addition to that, once it's been set, I'll need to ensure that rabbot "remembers" that setting between anything that forces it to re-establish any of these preconditions.

Just because I'm curious - are you working on some kind of reactive back-pressure mechanism in your service?

**Comment by Cyri-L** [comment]
Thank you for the swift reply Alex,

Indeed, making multiple instances on the same process is more about a conceptual thing, making my unit tests easier :) 

Regarding the dynamic prefetch, i need that exactly for the purpose you mentioned - backpressure mechanism - 
for the moment, I do something like this:
(it works even though I know this is an unstable procedure)

```js
this.prefetch = (count) => {
        let d = Q.defer();
        let queueChannel = rabbot.
            connections[SERVICE_NAME].channels["queue:" + Q_REQUESTS.name]
            .queue.channel;
        queueChannel.prefetch(count);
        rabbot.stopSubscription(Q_REQUESTS.name, SERVICE_NAME);
        setTimeout(function () {
            rabbot.startSubscription(Q_REQUESTS.name, Q_REQUESTS.exclusive, SERVICE_NAME);
            d.resolve();
        }, 30);
        return d.promise;
    };
```
I tried to digg into the multiple preconditions you listed above, but to be honest, i'm a bit lost into the whole process to make the dynamic prefetch stable.

Thus instead, i opted for another solution which is managing the pressure from the client side as all my microservices are in a trusted environment. (checking queue size before pushing)

In any case, thank you for this amazing library that eases the hassle of integrating rabbitmq.
Looking forward to the next improvements, 

Thank you !

**Comment by arobson** [comment]
@Cyri-L - I apologize that I'm only now getting to all the work you've put into this. I've pulled your code into master and 17 tests are failing. I have two options: we can look into reworking this PR as a whole or I can try and piece-meal rework your changes into various PRs.

Either way, I'll be adding you to the contributors list. I really appreciate how active you've become and all the bugs you've caught and improvements you're making. Let me know how'd you like to proceed.

It'll make things much easier if you submit single PRs with a test to cover the change. I like to try and have at least one test for a given change set so that we don't break things on accident in the future.

Thanks again!

**Pull request closed without merging**
