### PR TITLE
Handle returned messages from channels

### PR DESCRIPTION
**Pull request by rg1220**
Functionality to handle messages that were published to RabbitMQ but returned via the channel's `return` event.

Return event documentation:
http://www.squaremobius.net/amqp.node/channel_api.html#channel_events

### CODE REVIEW

**Comment by arobson** [comment]
@rg1220 - this is great. Can you add coverage for this under the integration spec by creating a test scenario where an unroutable message is published and returned?

Before line 680 in `spec/integration/integration.spec.js`, add a nested describe block for returned messages. In the before block, set up a `harness` by calling `harnessFn( done, 1 )` and then calling the `handle` call with the type of the message that will be returned. The harness will wait until it's received 1 returned message before calling the done callback in the before block so you'll publish a message with a mandatory flag that would be unroutable and then use an `it` to validate that the message you got back is what you sent.

Thank you again for the contribution, this is great!

**Comment by rg1220** [comment]
@arobson Should be good to go now. I modified the function signature for `topologyFn`, hence all the changes in topology.spec.js and now all tests are passing.

**Comment by rg1220** [comment]
Actually, I want to make the mandatory flag optional (unless you think otherwise) and I'll update the README as well.

**Comment by rg1220** [comment]
@arobson Now I'm happy with it 👍 Let me know if you want something changed/feel free to modify it to your liking.

**Pull request merged**
