### PR TITLE
update the machina verson

### PR DESCRIPTION
**Pull request by jainmohit**
Prototype Pollution https://nodesecurity.io/advisories/577

### CODE REVIEW

**Comment by dermidgen** [comment]
@arobson any chance of getting this PR merged soon?

**Comment by zlintz** [comment]
@dermidgen if you are interested checkout the fork https://github.com/Foo-Foo-MQ/foo-foo-mq

It has the updated version of machina and some other security advisory fixes

**Comment by dermidgen** [comment]
@zlintz oooooooooh noice. Thank you much!

**Comment by dermidgen** [comment]
@arobson so... I don't understand why this was just closed and not merged?  This is still a pretty good PR to merge.

Please reconsider

**Comment by dermidgen** [comment]
@arobson my bad.. Didn't see that you updated the README to officially point folks to https://github.com/Foo-Foo-MQ/foo-foo-mq

Thanks for Rabbot, it was great.

**Pull request closed without merging**
