### PR TITLE
Return promise on addConnection

### PR DESCRIPTION
**Pull request by mkozjak**

### CODE REVIEW

**Comment by arobson** [comment]
@mkozjak - thank you for the PR. Minor nitpick, currently this project uses when, would you please change your implementation to use `when.promise` for consistency? At some point, we can look at what it would take to converting the whole thing over, but for now, when is already in place and imported in the file.

**Comment by mkozjak** [comment]
Sure thing. I'll send you a PR.

**Comment by mkozjak** [comment]
@arobson: Ok, done.

**Comment by arobson** [comment]
@iamjochem - just look for the calls to `resolve` in the change set and you'll see the answer to your question :)

**Pull request merged**
